<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SCI-BD-L18-1576" failures="1" tests="5" name="TestClass" time="25.438" errors="0" timestamp="2024-05-11T17:11:31 BDT">
  <testcase classname="testcases.TestLogin" name="testLogInwithInalidCredentials" time="5.623">
    <failure type="java.lang.AssertionError" message="expected [Please enter a valid phone number.] but found [Incorrect username or password.]">
      <![CDATA[java.lang.AssertionError: expected [Please enter a valid phone number.] but found [Incorrect username or password.]
at testcases.TestLogin.testLogInwithInalidCredentials(TestLogin.java:18)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testLogInwithInalidCredentials -->
  <testcase classname="testcases.TestLogin" name="testLogInwithInalidCredentialsPassword" time="2.523"/>
  <testcase classname="testcases.TestLogin" name="testLoginWithInvalidCredentialsUsingDateProvider" time="4.41"/>
  <testcase classname="testcases.TestLogin" name="testLoginWithInvalidCredentialsUsingDateProvider" time="1.861"/>
  <testcase classname="testcases.HomePageTest" name="TestHomePageTitle" time="23.129"/>
</testsuite> <!-- TestClass -->
